#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Android.ExpandableSelector.Resource", IsApplication=false)]

namespace Xamarin.Android.ExpandableSelector
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int animation_duration = 2130771969;
			
			// aapt resource value: 0x7f010004
			public static int collapse_interpolator = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int container_interpolator = 2130771973;
			
			// aapt resource value: 0x7f010003
			public static int expand_interpolator = 2130771971;
			
			// aapt resource value: 0x7f010006
			public static int expandableItemStyle = 2130771974;
			
			// aapt resource value: 0x7f010000
			public static int hide_background_if_collapsed = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int hide_first_item_on_collapse = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public static int expandable_item_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int expandable_item_image_button = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] expandable_selector = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int expandable_selector_animation_duration = 1;
			
			// aapt resource value: 4
			public static int expandable_selector_collapse_interpolator = 4;
			
			// aapt resource value: 5
			public static int expandable_selector_container_interpolator = 5;
			
			// aapt resource value: 3
			public static int expandable_selector_expand_interpolator = 3;
			
			// aapt resource value: 0
			public static int expandable_selector_hide_background_if_collapsed = 0;
			
			// aapt resource value: 2
			public static int expandable_selector_hide_first_item_on_collapse = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
