#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.animation_duration = global::Sample.Resource.Attribute.animation_duration;
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.collapse_interpolator = global::Sample.Resource.Attribute.collapse_interpolator;
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.container_interpolator = global::Sample.Resource.Attribute.container_interpolator;
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.expand_interpolator = global::Sample.Resource.Attribute.expand_interpolator;
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.expandableItemStyle = global::Sample.Resource.Attribute.expandableItemStyle;
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.hide_background_if_collapsed = global::Sample.Resource.Attribute.hide_background_if_collapsed;
			global::Xamarin.Android.ExpandableSelector.Resource.Attribute.hide_first_item_on_collapse = global::Sample.Resource.Attribute.hide_first_item_on_collapse;
			global::Xamarin.Android.ExpandableSelector.Resource.Layout.expandable_item_button = global::Sample.Resource.Layout.expandable_item_button;
			global::Xamarin.Android.ExpandableSelector.Resource.Layout.expandable_item_image_button = global::Sample.Resource.Layout.expandable_item_image_button;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector = global::Sample.Resource.Styleable.expandable_selector;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector_animation_duration = global::Sample.Resource.Styleable.expandable_selector_animation_duration;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector_collapse_interpolator = global::Sample.Resource.Styleable.expandable_selector_collapse_interpolator;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector_container_interpolator = global::Sample.Resource.Styleable.expandable_selector_container_interpolator;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector_expand_interpolator = global::Sample.Resource.Styleable.expandable_selector_expand_interpolator;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector_hide_background_if_collapsed = global::Sample.Resource.Styleable.expandable_selector_hide_background_if_collapsed;
			global::Xamarin.Android.ExpandableSelector.Resource.Styleable.expandable_selector_hide_first_item_on_collapse = global::Sample.Resource.Styleable.expandable_selector_hide_first_item_on_collapse;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int animation_duration = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int collapse_interpolator = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int container_interpolator = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int expand_interpolator = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int expandableItemStyle = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int hide_background_if_collapsed = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int hide_first_item_on_collapse = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int black = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int brown = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int gray = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int green = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int orange = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int pink = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int white = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060005
			public const int background_radius = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int expandable_selector_margin = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int item_margin = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int item_size = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int item_text_size = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int item_text_size_small = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_expandable_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_expandable_selector_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_item_with_title = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int item_brown = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int item_green = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int item_orange = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int item_pink = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int monoandroidsplash = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int bt_close = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int es_sizes = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070001
			public const int custom_animation_duration = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int slow_custom_animation_duration = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int expandable_item_button = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int expandable_item_image_button = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_device_hub_black = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_gamepad_black = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ic_keyboard_arrow_down_black = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ic_keyboard_arrow_up_black = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ic_logo_karumi = 2130903044;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int collapse_button_text = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int colors_expandable_selector_title = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int ExpandableItemStyle = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int ExpandableItemStyleHeader = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Mono_Android_Theme_Splash = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] expandable_selector = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public const int expandable_selector_animation_duration = 1;
			
			// aapt resource value: 4
			public const int expandable_selector_collapse_interpolator = 4;
			
			// aapt resource value: 5
			public const int expandable_selector_container_interpolator = 5;
			
			// aapt resource value: 3
			public const int expandable_selector_expand_interpolator = 3;
			
			// aapt resource value: 0
			public const int expandable_selector_hide_background_if_collapsed = 0;
			
			// aapt resource value: 2
			public const int expandable_selector_hide_first_item_on_collapse = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
